### ISSUE TITLE
Make it easier to integrate auth with an existing app

### ISSUE THREAD

**Issue by bebraw** [GrumpyWizards/DarkLord#1]
I am developing a little API, [swagger-todo](https://github.com/bebraw/swagger-todo). I've stuck with jwt for auth but haven't implemented registration etc. yet. Given that it seems your project would fit my purposes very well with a little bit of tweaking. I think at least the following things would need to happen:

* Expose routes as a [Router](http://expressjs.com/api.html#router). After that it's possible to bind auth routes to some resource.
* Make it possible to customize database bits (I don't use `mongoose`). Ie. provide a standard interface to override.
* Make it possible to customize email sending. Ie. allow the user to hook up custom email sender etc. Maybe this can be merged with the interface above. It doesn't have to be email specific. It is enough there is some hook.
* Publish to NPM

In addition the following would be cool to have:

* Add a resource for refreshing token. You have this at todo but I thought to mention it given it's sort of important. Maybe it would be cool to have some automatic refresh for expiration after a normal query?
* Allow visible resources to be customized. Ie. in some cases you might not want to expose resources like `/register`.

Let me know if I can help you with this somehow!

**Comment by gregorypratt** [comment]
Hi, thanks for the feedback. I could work on point 2 as I use this myself in my own project. As far as email solutions go there isn't one and I don't really intend on building one, I'd rather not go that far. I understand allowing visible resources to be customisable and could sort that out, and the refreshing of tokens is actually complete, I just forgot to update the readme! I can publish it to NPM once it's in a better position. As for point 1 though I'll need your input as I don't fully understand it! Feel free to submit a PR and I'll review and no doubt learn a bit in the process ;-)

**Comment by bebraw** [comment]
>  As far as email solutions go there isn't one and I don't really intend on building one, I'd rather not go that far.

Yeah, no need. As long as there's a hook, something like [Nodemailer](http://www.nodemailer.com/) can be used.

> I understand allowing visible resources to be customisable and could sort that out, and the refreshing of tokens is actually complete, I just forgot to update the readme!

Great!

> As for point 1 though I'll need your input as I don't fully understand it!

I thought about it further. Wrapping the functionality within a `Router` isn't likely needed. Instead it could make sense to make a factory based API. Here's an example of what I mean:

```javascript
var DarkLord = require('DarkLord');

...

app.post('/token', DarkLord.token());
app.post('/register', DarkLord.register(function(...) {/* deal with registration now */}));
app.put('/change', DarkLord.change(function(...) {/* deal with pw change now */}));
... // you would have a factory like this for each feature
```

You would describe a standard interface for each feature in this approach. Ie. in my case I would use Sequelize and [passport-local-sequelize](https://www.npmjs.com/package/passport-local-sequelize) instead of Mongoose and its equivalent. The mongoose bits should be extracted out and pushed in perhaps another Node package (say `DarkLord-mongoose`). There could be another for Sequelize (`DarkLord-sequelize`). These bits could then be glued together (ie. `DarkLord.register(DarkLordMongo.register())` or something).

This would mean the core library would deal just with jwt related logic. The rest (ie. db, extra logic (email)) would be composed on top of that.

A good first step would be to extract the Mongo bits out of the current solution and define a rough API. After that another DB solution could be plugged in using the API to see how everything works out.

The API will take more thought than this but I hope this gives you a better idea of what I'm aiming at here.

**Comment by bebraw** [comment]
I noticed you have `POST /verify`. I guess the ideal flow would go like this:

1. POST /register
2. Send email to the user with an url containing verification token
3. Hit verification link. Given the link is in email shouldn't it be `GET /verify` since you cannot trigger POST trivially there?

How do you indent to use the verification status besides just setting the flag? What if a user doesn't verify an account? I understand the point here is that you shouldn't let the user use the service without forcing to verify first (so you know the user owns the email account).

**Comment by gregorypratt** [comment]
Ah yeah that should be a GET, I'll create an issue and update it.

As for the verify flag and process that's really up to the developer; they might want to totally ignore it and accept the registration itself as enough, or they might allow a certain amount of functionality to unverified users, or it's total lock down until verified - I'd rather not be that opinionated with something like this, unless there's a standard best practice or something

**Comment by bebraw** [comment]
> As for the verify flag and process that's really up to the developer; they might want to totally ignore it and accept the registration itself as enough, or they might allow a certain amount of functionality to unverified users, or it's total lock down until verified - I'd rather not be that opinionated with something like this, unless there's a standard best practice or something

That's true. Good point.

**Comment by bebraw** [comment]
As far as I can see this issue is almost ready to close. There is access to logic now and it is possible to override db logic through an interface.

You should still think about the APIs (ideally document these), remove direct dependency to mongo related bits (push to another module?) and publish it to NPM. After that I can give it a go against Sequelize.

How does that sound?

**Comment by gregorypratt** [comment]
Sounds good. It might take me a while to get my head around it, never done an NPM module before but I've just done `npm link` into another application locally and its starting to sink in. I'ld like to make the changes to make this an NPM module as I'll learn from it but feel free to submit a PR if I'm taking too long! :-)

**Comment by bebraw** [comment]
@gregorypratt I wrote [a little guide](http://www.nixtu.info/2015/02/how-to-publish-and-maintain-npm-packages.html) for you. Skip into the publishing part for relevant bits. It shouldn't take too much effort to get a release out I think. We can always iterate on the release.

**Comment by gregorypratt** [comment]
How is that looking? I think it's in a better position now. You configure it like so:

    require('DarkLord')({
      router: router,
      databaseSvc: require('./src/database.svc.sequelize.js'),
      user: User,
      secret: process.env.MY_TOKEN
    });

**router**: *optional* leave blank to build your own routes with the returned DarkLord object
**databaseSvc**: *optional* leave blank to default to mongoose
**user**:  *optional* a passport user, leave blank to default to predefined user model
**secret**: *optional* leave blank to default to `process.env.JWT_SECRET`

I'm thinking the databaseSvc could be plugin modules that you require in to handle different database solutions, so long as they follow this interface and return promises,

    {
      create: 
      update: 
      find: 
      findOne: 
      remove: 
    };

Documentation still outstanding...

**Comment by bebraw** [comment]
I think this is something I can work with. Over longer term it would be a good idea to split up the Mongo bit into a package of its own. You could even have a in-memory thinger for quick testing.

> I'm thinking the databaseSvc could be plugin modules that you require in to handle different database solutions, so long as they follow this interface and return promises

Yeah, this would be good. Ideally there could be a little test suite (another package) to test your adapter against. This can be taken to the level of whole API. Ie. test adapter and API default logic. This can be grown as a part of this project and then split up once you feel it's stable enough.

**Comment by gregorypratt** [comment]
Going to close this now its published. Further enhancements can be raised separately.

**Comment by bebraw** [comment]
Ok, I'll try to get a sequelize example based on DarkLord for you out there today.
