### ISSUE TITLE
register - `new User` is problematic as it might not work outside Mongoose

### ISSUE THREAD

**Issue by bebraw** [GrumpyWizards/DarkLord#12]
I started implementing the [sequelize demo](https://github.com/bebraw/darklord-sequelize) for DarkLord and ran into an issue with registration. It seems to crash at `new User` since Sequelize doesn't support that syntax. Would it be possible to run that piece of code through `databaseSvc.create`?

I think that `register` bit should work given it's provided by `passport-local-sequelize` (checked the code to confirm this).

**Comment by bebraw** [comment]
Do you want a PR for this? I guess simply replacing the bit with `create` would do for now.

**Comment by gregorypratt** [comment]
Feel free, a little snowed under at the mo!
