### ISSUE TITLE
Test against auth0 vulnerabilities

### ISSUE THREAD

**Issue by bebraw** [GrumpyWizards/DarkLord#14]
Just saw this: https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/ .

You might want to test against those cases just to be sure.

**Comment by gregorypratt** [comment]
I've submitted a Pull Request to the [node-jwt-simple](https://github.com/hokaccha/node-jwt-simple/issues/14) repo, although it doesn't seem that active. I might publish my fork of the project or switch libraries, keep you posted on this issue

**Comment by bebraw** [comment]
Alright, great.

Btw `passport-local-sequelize` is going to get a nice [PR](https://github.com/madhurjain/passport-local-sequelize/pull/7) merged soon. That will allow me to finish that Sequelize demo for DarkLord.
