### ISSUE TITLE
Customisable route visibility

### ISSUE THREAD

**Issue by gregorypratt** [GrumpyWizards/DarkLord#2]
Provide a way of turning routes on and off via a config file

**Comment by bebraw** [comment]
Is this relevant anymore now that there is access to the logic thanks to #10? If not, feel free to close.

**Comment by gregorypratt** [comment]
Nah, if you don't use `.router()` then you have to provide your own routes and at that point it's opt in. Closing issue

**Comment by bebraw** [comment]
Yeah, I would say there's plenty of customizability there right now. Just need to test drive it and document the APIs.
