### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by gregorypratt** [GrumpyWizards/DarkLord#3]
Once in a better more modular and customisable position

**Comment by bebraw** [comment]
I think it will be enough that you add `"main": "./features/auth/auth.ctrl.js"` to `package.json`. After that it should work as an entry point to the module. You can test it locally using `npm link`. You could try to replace `app.js` dependency to point at `DarkLord` or poke it via Node console once you have done that.

**Comment by gregorypratt** [comment]
Tested it locally and so far so good. Will publish it as is and further changes can be versioned updates

**Comment by gregorypratt** [comment]
https://www.npmjs.com/package/darklord
