### ISSUE TITLE
Expose routes as a Router

### ISSUE THREAD

**Issue by gregorypratt** [GrumpyWizards/DarkLord#4]
After that it's possible to bind auth routes to some resource.

**Comment by bebraw** [comment]
Here's what I propose. Let's factor `auth.ctrl` to return a Router by default. Ie. `app.js` would look like this:

```javascript
// before
// require('./features/auth/auth.ctrl')(router, databaseSvc, User);
// app.use('/', router);

// after
app.use('/', require('./features/auth/auth.ctrl')(databaseSvc, User).router());
```

Further customization can be provided an API like this:

```javascript
var Darklord = require('./features/auth/auth.ctrl')(databaseSvc, User)

...

app.use('/register', Darklord.register);
// etc.
```

This would provide the default API out of the box. The change is very simple to make. You simply move instantiation of a Router inside `auth.ctrl`. I can provide a PR for this.

**Comment by gregorypratt** [comment]
Please do and Ill give it a look and merge it in ;-)
