### ISSUE TITLE
Accept secret as a parameter

### ISSUE THREAD

**Issue by bebraw** [GrumpyWizards/DarkLord#6]
I noticed you load jwt secret from a fixed `./secret.json`. Ideally you would just inject the secret to the library.

Do you want me to prepare a PR about this for you?

**Comment by gregorypratt** [comment]
Shall I simply make use of environment variable with this?

**Comment by bebraw** [comment]
@gregorypratt In any case you'll end up with something to require (say `var DarkLord = require('darklord');`). It would feel most natural to accept just a parameter and let the user worry about how to get the secret (through a configuration file, env, whatnot). You could have something like this:

```javascript
var DarkLord = require('darklord');

...
DarkLord({
    secret: ... // load based on some conf, env etc.
});
```

This doesn't answer how to customize the library or hook it up with Express but you get the idea.

**Comment by gregorypratt** [comment]
I've changed it to an env var for now which is better than a file - until I've got some more time instead of over lunch! But I'll keep this issue open to continue with it

**Comment by bebraw** [comment]
Ok, cool.
